name: Centralized book generation

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    uses: SquareBracketAssociates/BookBuilderDashboard/.github/workflows/main.yml@master
    with:
      bookname: DataFrame-wip
